# setup.R
# Load required libraries
library(dplyr)
library(ggplot2)
library(fpp3)
library(patchwork)
library(tsibbledata)
library(urca)
library(astsa)
library(gridExtra)
library(vars)
library(fable)
library(feasts)
library(tidyquant)
library(quantmod)
library(purrr)
library(tidyverse)
suppressWarnings(library(quantmod))
