{
  "hash": "07e42e8e76b6e534de9a2aaaffb4ef2f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Activity40\"\nformat: \n  live-html:\n    theme:\n      light: [lux, theme-light.scss]\n      dark: [superhero, theme-dark.scss] \nengine: knitr\ntoc: true\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n## Modeling U.S. Inflation Dynamics: A Time Series Application\n\nThis analysis investigates U.S. inflation dynamics using **quarterly CPI**, **unemployment**, and **GDP** data from FRED. Inflation is defined as the quarterly percentage change in CPI:  \n$$\\text{inflation}_t = 100 \\times \\left(\\frac{CPI_t}{CPI_{t-1}} - 1\\right)$$\n\nThe modeling strategy integrates traditional time series approaches (AR and ARIMA) with structural diagnostics and modern multivariate frameworks to evaluate the influence of macroeconomic variables on inflation. Let's get the data first:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetSymbols(\"CPIAUCSL\", src = \"FRED\", auto.assign = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"CPIAUCSL\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncpi_data <- tibble(date = index(CPIAUCSL), CPI = as.numeric(CPIAUCSL[,1])) %>%\n  arrange(date) %>%\n  mutate(inflation = 100 * (CPI / lag(CPI) - 1)) %>%\n  mutate(Quarter = yearquarter(date)) %>% \n  as_tsibble(index = date) %>% \n  index_by(Quarter) %>%\n  summarize(CPI = mean(CPI), inflation = mean(inflation))\n\ngetSymbols(\"UNRATE\", src = \"FRED\", auto.assign = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"UNRATE\"\n```\n\n\n:::\n\n```{.r .cell-code}\nus_unemp <- data.frame(date = index(UNRATE), Unemployment = as.numeric(UNRATE$UNRATE)) %>%\n  as_tsibble(index = date) %>%\n  mutate(Quarter = yearquarter(date)) %>%\n  index_by(Quarter) %>%\n  summarize(Unemployment = mean(Unemployment))\n\ngetSymbols(\"GDP\", src = \"FRED\", auto.assign = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GDP\"\n```\n\n\n:::\n\n```{.r .cell-code}\nus_gdp <- data.frame(date = index(GDP), GDP = as.numeric(GDP$GDP)) %>%\n  as_tsibble(index = date) %>%\n  mutate(Quarter = yearquarter(date))\n\neconomic_data <- us_gdp %>%\n  inner_join(us_unemp, by = \"Quarter\") %>%\n  inner_join(cpi_data, by = \"Quarter\") %>%\n  mutate(GDP_growth = 100 * (GDP / lag(GDP) - 1)) %>%\n  dplyr::select(Quarter, date, GDP, GDP_growth, Unemployment, CPI, inflation) %>%\n  tidyr::drop_na()\n```\n:::\n\n\n\nSTL decomposition of the inflation series reveals clear seasonal and cyclical behavior. This reinforces the use of seasonal components in ARIMA models and motivates further refinement using explicitly seasonal structures.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neconomic_data %>%\n  as_tsibble(index = Quarter) %>%\n  model(STL(inflation ~ trend() + season())) %>%\n  components() %>%\n  autoplot()\n```\n\n::: {.cell-output-display}\n![](activity40_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n### **Step 1: AR(1) Regression**\n\nWe begin with an autoregressive model including lagged inflation, unemployment, and GDP growth. Residual diagnostics reveal no significant autocorrelation, implying the AR(1) structure is sufficient to capture temporal dependencies. \n\nThe model is of the form:\n\n$$\n\\text{Inflation}_t = \\beta_0 + \\beta_1 \\cdot \\text{GDP\\_growth}_t + \\beta_2 \\cdot \\text{Unemployment}_t + \\eta_t\n$$\n\nwhere $( \\eta_t \\sim \\text{ARIMA}(3,0,1)).$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narima_model <- economic_data %>%\n  as_tsibble(index = Quarter) %>%\n  model(ARIMA(inflation ~ GDP_growth + Unemployment))\n\nreport(arima_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: inflation \nModel: LM w/ ARIMA(3,0,1) errors \n\nCoefficients:\n         ar1     ar2     ar3      ma1  GDP_growth  Unemployment  intercept\n      0.6260  0.0543  0.1793  -0.3189      0.0398       -0.0335     0.4109\ns.e.  0.2307  0.1048  0.0996   0.2395      0.0099        0.0150     0.1033\n\nsigma^2 estimated as 0.04254:  log likelihood=52.18\nAIC=-88.36   AICc=-87.88   BIC=-58.55\n```\n\n\n:::\n\n```{.r .cell-code}\narima_model %>% \n  residuals() %>% \n  features(.resid, ~ljung_box(.x, lag = 10)) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|.model                                       |  lb_stat| lb_pvalue|\n|:--------------------------------------------|--------:|---------:|\n|ARIMA(inflation ~ GDP_growth + Unemployment) | 8.922994| 0.5394271|\n\n\n:::\n:::\n\n\n\nThe Ljung-Box diagnostics show no strong autocorrelation, indicating the AR(1) structure with regressors reasonably captures short-term dynamics.\n\n### **Step 2: ARIMA-X Model**\n\nWe improve upon this by fitting an ARIMA model with exogenous regressors using `forecast::auto.arima()`, which also allows for seasonal ARMA components. The best-fit specification is an ARIMA(3,0,3)(2,0,2)[4], indicating both short- and medium-term seasonal effects. \n\nThis yields a model of the form:\n\n$$\n\\text{Inflation}_t = \\beta_0 + \\beta_1 \\cdot \\text{GDP\\_growth}_t + \\beta_2 \\cdot \\text{Unemployment}_t + \\eta_t\n$$\n\nwhere $(\\eta_t \\sim \\text{ARIMA}(3,0,3)(2,0,2)_4)$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\nxreg_matrix <- economic_data %>% as_tibble() %>% \n  dplyr::select(GDP_growth, Unemployment) %>%\n  data.matrix()\n\nstart_year <- year(min(economic_data$Quarter))\nstart_month <- month(min(economic_data$Quarter))\ninflation_ts <- ts(economic_data$inflation, frequency = 4, start = c(start_year, start_month))\n\narimax_model <- auto.arima(inflation_ts, xreg = xreg_matrix)\n\nsummary(arimax_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: inflation_ts \nRegression with ARIMA(3,0,3)(2,0,2)[4] errors \n\nCoefficients:\n          ar1     ar2     ar3     ma1     ma2      ma3     sar1     sar2\n      -0.3160  0.2542  0.8826  0.6122  0.1032  -0.5369  -0.3004  -0.0796\ns.e.   0.0779  0.0569  0.0726  0.1158  0.0978   0.1127   0.3286   0.2993\n        sma1     sma2  intercept  GDP_growth  Unemployment\n      0.3459  -0.1138     0.4139      0.0355       -0.0328\ns.e.  0.3350   0.3070     0.1031      0.0097        0.0139\n\nsigma^2 = 0.04171:  log likelihood = 58\nAIC=-88   AICc=-86.56   BIC=-35.82\n\nTraining set error measures:\n                       ME      RMSE       MAE       MPE     MAPE      MASE\nTraining set -0.001319576 0.1998711 0.1407113 -5006.591 5083.211 0.6846118\n                  ACF1\nTraining set 0.0108953\n```\n\n\n:::\n\n```{.r .cell-code}\narimax_model %>% \n  residuals() %>% \n  ljung_box(lag = 10) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|          |         x|\n|:---------|---------:|\n|lb_stat   | 5.9605728|\n|lb_pvalue | 0.8185648|\n\n\n:::\n:::\n\n\n\nThe Ljung-Box gives us larger p-value this time, and the residuals should be more like white noise.\n\n\n### **Activity 1: Write model equations for the ARIMA model in Step 1**\n\nThe fitted model is a **linear regression with ARIMA(3,0,1) errors**, often called an **ARIMA with exogenous regressors (ARIMAX)**. The equation form is:\n\n\n\n```{=latex}\n\\begin{aligned}\n\\text{inflation}_t &= \\beta_0 + \\beta_1 \\cdot \\text{GDP\\_growth}_t + \\beta_2 \\cdot \\text{Unemployment}_t + \\eta_t \\\\\n\\eta_t &= \\phi_1 \\eta_{t-1} + \\phi_2 \\eta_{t-2} + \\phi_3 \\eta_{t-3} + \\theta_1 \\varepsilon_{t-1} + \\varepsilon_t \\\\\n\\varepsilon_t &\\sim \\text{WN}(0, \\sigma^2)\n\\end{aligned}\n```\n\n\n\nWhere:\n\n- $\\beta_1 = 0.0398$ (GDP growth has a positive effect)\n- $\\beta_2 = -0.0335$ (unemployment has a negative effect)\n- $\\phi_1, \\phi_2, \\phi_3$ are AR terms\n- $\\theta_1$ is the MA(1) term\n- $\\sigma^2 = 0.04254$ is the estimated variance of white noise\n\n\n### **Activity 2: Residual Diagnostics**\n\nExamine ACF/PACF plots and Ljung-Box test results for the ARIMA model. Interpret residual autocorrelation and explain why traditional AR(1) structures may fail in macroeconomic contexts.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gridExtra)\ngg_tsresiduals(arima_model) + ggtitle(\"LM w/ ARIMA(3,0,1)\")\n```\n\n::: {.cell-output-display}\n![](activity40_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncheckresiduals(arimax_model) \n```\n\n::: {.cell-output-display}\n![](activity40_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(3,0,3)(2,0,2)[4] errors\nQ* = 6.1871, df = 3, p-value = 0.1029\n\nModel df: 10.   Total lags used: 13\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1,2))\npacf(residuals(arima_model), lag.max = 24) \npacf(residuals(arimax_model), lag.max = 24) \n```\n\n::: {.cell-output-display}\n![](activity40_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n:::\n\n\n\n\n### **Activity 3: Variable Transformation**\n\nTo address potential nonstationarity and heteroskedasticity, GDP is log-transformed and unemployment is differenced. An ARIMA(4,0,0) model with these transformed covariates yields a competitive AIC and improved interpretability. What do the results suggests? Why are the transformations needed?\n\n- Log(GDP) is positively associated with inflation.\n- Changes in unemployment are negatively associated with inflation.\n\nThese transformations help stabilize variance and center the series around a constant mean.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neconomic_data <- economic_data %>%\n  mutate(log_GDP = log(GDP),\n         delta_Unemployment = difference(Unemployment)) %>%\n  drop_na()\n\narima_transformed <- Arima(\n  ts(economic_data$inflation, frequency = 4, start = c(1948, 2)),\n  order = c(4, 0, 0),\n  xreg = cbind(log_GDP = economic_data$log_GDP,\n               delta_Unemployment = economic_data$delta_Unemployment)\n)\n\nsummary(arima_transformed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts(economic_data$inflation, frequency = 4, start = c(1948, 2)) \nRegression with ARIMA(4,0,0) errors \n\nCoefficients:\n         ar1     ar2     ar3      ar4  intercept  log_GDP  delta_Unemployment\n      0.3512  0.1753  0.2749  -0.0209     0.1994   0.0092             -0.0340\ns.e.  0.0579  0.0596  0.0594   0.0584     0.2932   0.0354              0.0154\n\nsigma^2 = 0.04305:  log likelihood = 50.18\nAIC=-84.36   AICc=-83.87   BIC=-54.57\n\nTraining set error measures:\n                      ME      RMSE       MAE      MPE    MAPE      MASE\nTraining set 0.001433048 0.2050985 0.1427111 -4527.97 4608.29 0.7022001\n                    ACF1\nTraining set 0.008634326\n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(arima_transformed)\n```\n\n::: {.cell-output-display}\n![](activity40_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(4,0,0) errors\nQ* = 6.4755, df = 4, p-value = 0.1663\n\nModel df: 4.   Total lags used: 8\n```\n\n\n:::\n:::\n\n\n\n\n### **Activity 4: VAR model**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vars)\nvar_data <- economic_data %>% as_tibble() %>% \n  tidyr::drop_na() %>% \n  dplyr::select(inflation, GDP_growth, delta_Unemployment)\n\nlag_order <- VARselect(var_data, type = \"const\")$selection[\"AIC(n)\"]\nvar_model <- VAR(var_data, p = lag_order)\nsummary(var_model$varresult$inflation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ -1 + ., data = datamat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.38107 -0.09893 -0.00104  0.09479  0.63060 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \ninflation.l1           0.28733    0.05904   4.867 1.85e-06 ***\nGDP_growth.l1          0.02681    0.01558   1.720  0.08641 .  \ndelta_Unemployment.l1  0.02672    0.02548   1.049  0.29525    \ninflation.l2           0.11125    0.06018   1.849  0.06553 .  \nGDP_growth.l2          0.01770    0.01628   1.087  0.27804    \ndelta_Unemployment.l2  0.01155    0.02710   0.426  0.67026    \ninflation.l3           0.19814    0.05969   3.320  0.00102 ** \nGDP_growth.l3          0.04183    0.01614   2.591  0.01004 *  \ndelta_Unemployment.l3  0.04544    0.02608   1.742  0.08248 .  \nconst                 -0.01775    0.02940  -0.604  0.54648    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2016 on 293 degrees of freedom\nMultiple R-squared:  0.474,\tAdjusted R-squared:  0.4578 \nF-statistic: 29.34 on 9 and 293 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(var_model$varresult$inflation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -98.79102\n```\n\n\n:::\n:::\n\n\n\nThis yields a model of the form:\n\n\n\n```{=latex}\n\\begin{aligned}\n\\text{inflation}_t &= \\alpha_0 + \\alpha_1 \\cdot \\text{inflation}_{t-1} + \\alpha_2 \\cdot \\text{GDP\\_growth}_{t-1} + \\alpha_3 \\cdot \\Delta \\text{Unemployment}_{t-1} \\\\\n&\\quad + \\alpha_4 \\cdot \\text{inflation}_{t-2} + \\alpha_5 \\cdot \\text{GDP\\_growth}_{t-2} + \\alpha_6 \\cdot \\Delta \\text{Unemployment}_{t-2} \\\\\n&\\quad + \\alpha_7 \\cdot \\text{inflation}_{t-3} + \\alpha_8 \\cdot \\text{GDP\\_growth}_{t-3} + \\alpha_9 \\cdot \\Delta \\text{Unemployment}_{t-3} + \\varepsilon_t\n\\end{aligned}\n```\n\n\n\nwhere $\\varepsilon_t \\sim \\text{WN}(0, \\sigma^2)$, and lag order $p=3$ was selected by AIC.\n\n",
    "supporting": [
      "activity40_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}